config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :vlogs do
   resources :comments
   resources :likes
  end
  get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'vlogs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vlog.rb
class Vlog < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_many :likes
	validates :title, :content, presence: true
	has_one_attached :file
end

app/controllers/vlogs_controller.rb
require 'securerandom'
require 'pp'

@expire_val = 100.minutes

class VlogsController < ApplicationController
  before_action :set_vlog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /vlogs or /vlogs.json
  def index
    ##avoid duplicate cache
    if params[:page].nil?
        params[:page] = 1
    end
    #@vlogs = Vlog.all.order('updated_at DESC')
    @vlogs = Rails.cache.fetch("vlogs_page/#{params[:page]}", expires_in: @expire_val) do
          #add pagination
      Vlog.includes(:user, :comments, :likes).paginate(page: params[:page], per_page: 3).order('updated_at DESC').to_a
    end
    #to combine sql, comment out one line above
    #@vlogs = Vlog.includes(:user, :comments, :likes).paginate(page: 
    #  params[:page], per_page: 3).order('updated_at DESC')
  end

  # GET /vlogs/1 or /vlogs/1.json
  def show
    #@vlog = Rails.cache.fetch("vlog/#{params[:id]}", expires_in: @expire_val) do
    #  Vlog.includes(:likes).find_by(id: params[:id])
    #end
    ##avoid duplicate cache
    if params[:page].nil?
      params[:page] = 1
    end
    @vlog_comments = Rails.cache.fetch("vlog_comments/#{params[:id]}/#{params[:page]}", expires_in: @expire_val) do
      @vlog.comments.includes(:user).paginate(page: params[:page], per_page: 3).order('created_at DESC').to_a
    end

    @attachment = @vlog.file_uuid
    @actype = @vlog.file_type
    
    #to combine sql, comment out on one line above
    #@vlog_comments = @vlog.comments.includes(:user).paginate(page: params[:page], per_page: 3).order('created_at DESC')
    
    @vlog_likes = Rails.cache.fetch("vlog_likes_count/#{params[:id]}", expires_in: @expire_val) do
      @vlog.likes.length()
    end

    @vlog_comments_count = Rails.cache.fetch("vlog_comments_count/#{params[:id]}", expires_in: @expire_val) do
      @vlog_comments.total_entries
    end
  end

  # GET /vlogs/new
  def new
    if user_signed_in?
      @vlog = current_user.vlogs.build
    else
      @vlog = Vlog.new
    end
  end

  # GET /vlogs/1/edit
  def edit
  end

  def correct_user
    @vlog = current_user.vlogs.find_by(id: params[:id])
    redirect_to vlogs_path, notice: "Not Authorized To Edit This Vlog!" if @vlog.nil?
    #
    #
  end

  # POST /vlogs or /vlogs.json
  def create
    if user_signed_in?
      @vlog = current_user.vlogs.build(vlog_params)
    else
      @vlog = Vlog.new(vlog_params)
    end
    # @vlog.file_uuid, @vlog.file_type = handle_uploaded_file(params)
    respond_to do |format|
      if @vlog.save
        format.html { redirect_to @vlog, notice: "Vlog was successfully created." }
        format.json { render :show, status: :created, location: @vlog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vlogs/1 or /vlogs/1.json
  def update
    # params.require(:vlog)[:file_uuid], params.require(:vlog)[:file_type] = handle_uploaded_file(params)
    respond_to do |format|
      if @vlog.update(vlog_params)
        format.html { redirect_to @vlog, notice: "Vlog was successfully updated." }
        format.json { render :show, status: :ok, location: @vlog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vlogs/1 or /vlogs/1.json
  def destroy
    @vlog.destroy
    respond_to do |format|
      format.html { redirect_to vlogs_url, notice: "Vlog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vlog
      #@vlog = Vlog.find(params[:id])
      @vlog = Rails.cache.fetch("vlog/#{params[:id]}", expires_in: @expire_val) do
            Vlog.includes(:likes, :user).find_by(id: params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def vlog_params
      params.require(:vlog).permit(:title, :content, :user_name, :user_id, :file_uuid, :file_type)
    end
end

app/helpers/vlogs_helper.rb
module VlogsHelper
end

app/views/vlogs/_form.html.erb
<%= form_with(model: vlog) do |form| %>
  <% if vlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vlog.errors.count, "error") %> prohibited this vlog from being saved:</h2>

      <ul>
        <% vlog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_area :content, class:"form-control",style:"min-height: 500px;line-height: 20px;", placeholder:"Content"%>
  </div>
  <div class="field form-group">
      <%= form.text_field :file_uuid, class:"form-control", placeholder:"S3 URL" %>
      <%= form.text_field :file_type, class:"form-control", placeholder:"File Type" %>
    </div>
  <br/>
  <% if user_signed_in? %>
    <div class="field form-group">
      <%= form.text_field :user_name, class:"form-control", placeholder:"Publisher", value:current_user.email.split('@',0)[0] +"_" +  current_user.id.to_s, type: :hidden%>
    </div>
  
    <div class="field form-group">
      <%= form.number_field :user_id, id: :vlog_user_id, class:"form-control", placeholder:"User Id", value:current_user.id, type: :hidden%>
    </div>
  <% else %>
    <div class="field form-group">
      <%= form.text_field :user_name, class:"form-control", placeholder:"Publisher", value: "Anonymous", type: :hidden %>
    </div>
  
    <div class="field form-group">
      <%= form.number_field :user_id, id: :vlog_user_id, class:"form-control", placeholder:"User Id", value:5, type: :hidden%>
    </div>
    
  <% end %>
  
  <div class="actions">
    <%= form.submit class:"btn btn-info"%>
  </div>
<% end %>

app/views/vlogs/edit.html.erb
<div class="card" style="width: 80%;margin: AUTO;">
<h1>Editing Vlog</h1>
<div class="card-body">
<%= render 'form', vlog: @vlog %>
</div>
<br/>
<div class="card-footer bg-transparent border-success">
<%= link_to 'Show', @vlog, class:"btn btn-primary"%> 
<%= link_to 'Back', vlogs_path, class:"btn btn-primary" %>
<%= link_to 'Delete', @vlog, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %>
</div>
</div>

app/views/vlogs/index.html.erb
<div style="width: 80%;margin: AUTO;">
  <h1>Vlogs</h1>

  <div class="flickr_pagination">
  <%= will_paginate @vlogs, renderer: BootstrapPagination::Rails %>
  </div>
  <br/>
  <% @vlogs.each do |vlog| %>
    <div class="card  bg-light mb-3">
      <h4 class="card-header">
        <%= link_to vlog.title, vlog, style:"text-decoration: none;" %>
      </h4>
      <div class="card-body">
          <p class="card-text">
            <%= vlog.content[0,100] %>
            <%if vlog.content.length > 100 %>
                ...
            <%end%>       
          </p>

          <p class="card-text">
            User 
            <% if vlog.user_id == 5 %>
                Anonymous
            <%else%>
                <%= vlog.user_id%>
                  <%if vlog.user.nil?%>
                    (Account Cancled)
                  <%end%>
            <%end%>
            / <%= vlog.updated_at %> / </td>
            <strong><%= vlog.likes.length() %> likes ♥️ / </strong>
            <strong><%= vlog.comments.length() %> comments</strong>
          </p>
        
    </div>
    <div class="card-footer bg-transparent border-success">
      <%= link_to 'Show', vlog, class:"btn btn-outline-primary btn-sm"%>
      <% if user_signed_in? and vlog.user == current_user%>
          <%= link_to 'Delete', vlog, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-outline-danger btn-sm" %>
        <% end %>
    </div>
    </div>
  <% end %>

<br/>
<%= link_to 'New Vlog', new_vlog_path, class:"btn btn-primary"%>
</div>
<br/>

app/views/vlogs/new.html.erb
<div class="card" style="width: 80%;margin: AUTO;">
  <div class="card-body">
	<h1>New Vlog</h1>
	
	<%= render 'form', vlog: @vlog %>
	<br/>
</div>
</div>
<br/>
<div style="width: 80%;margin: AUTO;">
	<%= link_to 'Back', vlogs_path%>
</div>

app/views/vlogs/show.html.erb
<div class="card text-center", style="width: 80%;margin: AUTO;">
  <div class="card-header">
    <h2> <%= @vlog.title %> </h2>
  </div>
  <div class="card-body">
    <p class="card-text", style="text-align:left;font-size: 16px;"><%= @vlog.content %></p>
    <% if /video/.match @actype %>
      <%= video_tag @attachment %>
    <% elsif /image/.match  @actype %>
      <%= image_tag @attachment %>
    <% else %>
      <%= link_to 'Download', @attachment, class:"btn btn-primary btn-sm" %>
    <%end%>
  </div>
  <div class="card-footer text-muted">
    <% if @vlog.user_id == 5 %>
    <strong> Author: Anonymous </strong>
    <% else %>
    <strong> Author: <%= @vlog.user_id%></strong>
    <%if @vlog.user.nil?%>
            (Account Cancled)
    <%end%>
    <% end %>
    <br/>
    <strong>Created:</strong>
    <%= @vlog.created_at %>
    <br/>
    <strong>Updated:</strong>
    <%= @vlog.updated_at %>
    <br/>
    <br/>
    <%= link_to 'Back', vlogs_path, class:"btn btn-primary btn-sm" %>
    <% if user_signed_in? and @vlog.user == current_user %>
    <%= link_to 'Edit', edit_vlog_path(@vlog), class:"btn btn-primary btn-sm"%> 
    <%= link_to 'Delete', @vlog, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %>
    <% end %>
  </div>
</div>
<br/>

<div class="card", style="width: 80%;margin: AUTO;">
  <div class="card-body">
  <%= render "likes/new" %>
  <br>
  <%= render "comments/form"%>
  <br/>
  <%#<%= render vlog_comments_path(@vlog.id) %>
  <strong><%=  @vlog_likes %> likes ♥️ / </strong>
  <strong><%=  @vlog_comments_count %> comments:</strong>
  <br/>
  <br/>
  <div class="apple_pagination bg-white border-white">
    <%= will_paginate @vlog_comments%>
  </div>
  <%= render @vlog_comments %>

  <%#<%= will_paginate @vlog.comments, renderer: BootstrapPagination::Rails %>

  </div>
</div>

app/views/vlogs/table.html.erb
<%
=begin %>
<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>User name</th>
        <th>User Id</th>
        <th>Latest Update</th>
        <%if user_signed_in? %>
          <th colspan="1"></th>
        <%end%>
      </tr>
    </thead>
  <tbody>
    <% @vlogs.each do |vlog| %>
      <tr>
        <td><%= link_to vlog.title, vlog, style:"text-decoration: none;" %></td>

        <td><%= vlog.content[0,100] %>
            <%if vlog.content.length > 100 %>
             ...
            <%end%>
        </td>

        <td><%= vlog.user_name %></td>

        <% if vlog.user_id == 5 %>
          <td> Anonymous</td>
        <%else%>
          <td><%= vlog.user_id%>
          <%if vlog.user.nil?%>
            (Account Cancled)
          <%end%>
          </td>
        <%end%>

        <td><%= vlog.updated_at %></td>

        <% if user_signed_in? and vlog.user == current_user%>
          <td><%= link_to 'Delete', vlog, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %> </td>
        <%elsif user_signed_in? %>
          <td> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
=end%>