config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :vlogs do
   resources :comments
   resources :likes
  end
  get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'vlogs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :vlog
  belongs_to :user
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:new, :create, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /comments or /comments.json
  def index
    #@comments = Comment.all
    @comments = Comment.find_by(vlog_id: params[:vlog_id])
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to Vlog.find(params[:vlog_id]), notice: "Not Authorized To Edit This Vlog!" if @comment.nil?
    ##{params}
  end
  # GET /comments/new
  def new
    @vlog = Vlog.find(params[:vlog_id])
    @comment = @vlog.comments.build
  end

  # GET /comments/1/edit
  def edit
    @vlog = Vlog.find(params[:vlog_id])
    @comment = @vlog.comments.find(params[:id])
  end

  def create
    @vlog = Vlog.find(params[:vlog_id])
    @comment = @vlog.comments.create(params[:comment].permit(:comment))

    if user_signed_in?
      @comment.user_id = current_user.id
    else
      @comment.user_id = 5
    end
    respond_to do |format|
      if @comment.save
        format.html {redirect_to @vlog, notice: "Comment was successfully created." }
        #format.html {redirect_to vlog_comment_path(@vlog.id, @comment.id), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  # POST /comments or /comments.json
  #def create
  #  @vlog = Vlog.find(params[:vlog_id])
  #  @comment = @vlog.comments.create(params[:comment].permit(:comment))
#
  #  if @comment.save
  #    redirect_to @vlog, notice: "Comment was successfully created."
  #    render :show, status: :created, location: @comment
  #  else
  #    render :new, status: :unprocessable_entity
  #  end

    #@comment = Comment.new(comment_params)

    #respond_to do |format|
    #  if @comment.save
    #    format.html { redirect_to @comment, notice: "Comment was successfully created." }
    #    format.json { render :show, status: :created, location: @comment }
    #  else
    #    format.html { render :new, status: :unprocessable_entity }
    #    format.json { render json: @comment.errors, status: :unprocessable_entity }
    #  end
    #end
  #end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    @vlog = Vlog.find(params[:vlog_id])
    @comment = @vlog.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to vlog_comment_path(@vlog.id, @comment.id), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @vlog = Vlog.find(params[:vlog_id])
    @comment = @vlog.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to vlog_path(@vlog), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:comment, :vlog_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%if comment.comment.nil? %>
<br/>
<%else%>
  <%= comment.created_at %>
  <% if comment.user_id == 5%>
  	Anonymous User
  <% else %>
    User <%= comment.user_id %>
    <%if comment.user.nil?%>
        (Account Cancled)
    <%end%>
  <% end %>
  commented:
  <div class="card">
    <div class="card-body">
      <%= comment.comment%>
      <br/>
     </div>
     <div class="card-footer text-muted">
      <%#= link_to "Show", vlog_comment_path(@vlog.id, comment.id), class:"btn btn-outline-info btn-sm" %>
      <% if user_signed_in? and comment.user == current_user %>
        <strong>
        <%= link_to "Edit", edit_vlog_comment_path(comment.vlog, comment), class:"btn btn-outline-info btn-sm" %>
        <%= link_to 'Delete Comment', [comment.vlog, comment], method: :delete, data: { confirm: 'Are you sure?'},  class:'btn btn-outline-danger btn-sm'%>
        </strong>
      <% end %>
    </div>
  </div>
  <br/>
  <br/>
<%end%>

app/views/comments/_form.html.erb
<%= form_for([@vlog, @vlog.comments.build]) do |form| %>

  <div class="field form-group">
    <div class="actions">
    <%= form.submit class:"btn btn-primary btn-sm"%>
    </div>
    <%= form.text_area :comment, class:"form-control", placeholder:"New Comment" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :vlog_id, class:"form-control", type: :hidden%>
  </div>

  <% if user_signed_in?%>
    <div class="field form-group">
      <%= form.number_field :user_id, class:"form-control", value:current_user.id, type: :hidden%>
    </div>
  <%else%>
    <div class="field form-group">
      <%= form.number_field :user_id, class:"form-control", value:5, type: :hidden%>
    </div>
  <%end%>
<% end %>

app/views/comments/ddd_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :"Add New Comment" %>
    <%= form.text_area :comment, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :vlog_id, class:"form-control", type: :hidden%>
  </div>

  <% if user_signed_in?%>
    <div class="field form-group">
      <%= form.text_field :user_id, class:"form-control", value:current_user.id, type: :hidden%>
    </div>
  <%else%>
    <div class="field form-group">
      <%= form.text_field :user_id, class:"form-control", value:5, type: :hidden%>
    </div>
  <%end%>
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="card" style="width: 80%;margin: AUTO;">
  <div class="card-body">
    <h1>Editing Comment</h1>

    <%= form_for([@vlog, @comment]) do |form| %>

      <div class="field form-group">
        <%= form.label :"Add New Comment" %>
        <%= form.text_area :comment, class:"form-control" %>
      </div>

      <div class="field form-group">
        <%= form.text_field :vlog_id, class:"form-control", type: :hidden%>
      </div>

      <% if user_signed_in?%>
        <div class="field form-group">
          <%= form.text_field :user_id, class:"form-control", value:current_user.id, type: :hidden%>
        </div>
      <%else%>
        <div class="field form-group">
          <%= form.text_field :user_id, class:"form-control", value:5, type: :hidden%>
        </div>
      <%end%>
      <br/>
      <div class="actions">
        <%= form.submit class:"btn btn-primary"%>
        <%= link_to 'Delete Comment', [@comment.vlog, @comment], method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-danger'%>
        <br/>
      </div>
    <% end %>
 </div>
</div>
<br/>
<div style="width: 80%;margin: AUTO;">
  <%= link_to 'Back To Vlog', @comment.vlog%>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Vlog</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.vlog_id %></td>
        <td><%= comment.user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_vlog_comment_path %>

app/views/comments/new.html.erb
<div class="card" style="width: 80%;margin: AUTO;">
  <div class="card-body">
	<h1>New Comment</h1>
	
	<%= render 'form', comment: @comment %>
	<br/>
</div>
</div>
<br/>
<div style="width: 80%;margin: AUTO;">
	<%= link_to 'Back', @vlog%>
</div>

app/views/comments/show.html.erb
<div class="card text-center", style="width: 80%;margin: AUTO;">
  <div class="card-header">
    <h2> Comment </h2>
  </div>
  <div class="card-body">
    <p class="card-text", style="text-align:left;font-size: 16px;"><%= @comment.comment %></p>
  </div>
  <div class="card-footer text-muted">
    <% if @comment.user_id == 5 %>
      <strong>Author: Anonymous </strong>
    <% else %>
      <strong> Author: <%= @comment.user_id%></strong>
    <% end %>
    <br/>
    <strong>Created:</strong>
    <%= @comment.created_at %>
    <br/>
    <strong>Updated:</strong>
    <%= @comment.updated_at %>
    <br/>
    <br/>
    <% if user_signed_in? and @comment.user == current_user %>
      <strong>
        <%= link_to "Edit", edit_vlog_comment_path(@comment.vlog, @comment), class:"btn btn-outline-info btn-sm" %>
        <%= link_to 'Delete Comment', [@comment.vlog, @comment], method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-outline-danger btn-sm'%>
        </strong>
    <% end %>
  </div>
</div>
<br/>

  <div style="width: 80%;margin: AUTO;">
  <%= link_to 'Back To Vlog', @comment.vlog%>
  </div>  