config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :vlogs do
   resources :comments
   resources :likes
  end
  get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'vlogs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<a class="navbar-brand" href="#">
      <img src="/redcup.jpg" alt="" width="30" height="24" class="d-inline-block align-text-top">
      <%= link_to 'RedCup Community', root_path, class:"navbar-brand"%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Show Vlogs', vlogs_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Post New Vlog', new_vlog_path, class:"nav-link"%>
        </li>

        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Account', edit_user_registration_path, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1 style="text-align:center;"> RedCup Team Members </h1>

<div class="accordion" id="accordionExample" style="width: 60%;margin: AUTO;">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Chaofan
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
       <strong>RedCup Team Member </strong>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Lijuan
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
       <strong>RedCup Team Member </strong>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Xinyu
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>RedCup Team Member </strong>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Zuying
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>RedCup Team Member </strong>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div style="text-align: center;">
<h1>RedCup</h1>
<br/>
<p>Wellcome to RedCup Comminity!</p>
</div>